name: Education Lab Architects
favicon: null
layout_spectrum: 0.1291383362840861
typography_spectrum: 0.7521497765555978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8213437327649444
  lightness: 0.46122191892936826
  saturation: 0.9587802137248218
  rhythmicContrast: 0.7465415182523429
purpose: []
